2017-04-15 05:21:24,296 [Thread-3:123145314922496] [django.request:132] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view blog.views.index didn't return an HttpResponse object. It returned None instead.
2017-04-15 05:21:50,404 [Thread-3:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/css/base.css
2017-04-15 05:21:50,407 [Thread-4:123145314922496] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/css/index.css
2017-04-15 05:21:50,409 [Thread-5:123145319129088] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/js/jquery.min.js
2017-04-15 05:21:50,411 [Thread-6:123145323335680] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/js/sliders.js
2017-04-15 05:21:50,413 [Thread-7:123145327542272] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/js/nav.js
2017-04-15 05:21:50,439 [Thread-9:123145314922496] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/js/sliders.js
2017-04-15 05:21:50,439 [Thread-8:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a1.jpg
2017-04-15 05:21:50,478 [Thread-10:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a2.jpg
2017-04-15 05:21:50,481 [Thread-11:123145314922496] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a3.jpg
2017-04-15 05:21:50,485 [Thread-12:123145319129088] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/js/nav.js
2017-04-15 05:21:50,488 [Thread-13:123145323335680] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a4.jpg
2017-04-15 05:21:50,503 [Thread-14:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a1.jpg
2017-04-15 05:21:50,518 [Thread-15:123145314922496] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a2.jpg
2017-04-15 05:21:50,521 [Thread-16:123145319129088] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a3.jpg
2017-04-15 05:27:49,754 [Thread-23:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a1.jpg
2017-04-15 05:27:49,765 [Thread-24:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a2.jpg
2017-04-15 05:27:49,775 [Thread-25:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a3.jpg
2017-04-15 05:27:49,787 [Thread-26:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a4.jpg
2017-04-15 05:27:55,629 [Thread-41:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a1.jpg
2017-04-15 05:27:55,641 [Thread-42:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a2.jpg
2017-04-15 05:27:55,654 [Thread-43:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a3.jpg
2017-04-15 05:27:55,666 [Thread-44:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /blog/index/images/a4.jpg
2017-04-15 07:34:40,896 [Thread-2:123145310715904] [django.request:152] [base:get_response] [WARNING]- Not Found: /
2017-04-15 07:34:44,628 [Thread-5:123145319129088] [django.request:152] [base:get_response] [WARNING]- Not Found: /
2017-04-15 14:39:55,780 [Thread-7:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uploads/avatar/default.png
2017-04-15 15:02:09,559 [Thread-2:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uplpads/2017/04/login.jpg/
2017-04-15 15:03:06,225 [Thread-5:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uploads/2017/04/login.jpg/
2017-04-15 15:03:43,116 [Thread-6:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uploads/2017/04/login.jpg
2017-04-15 15:04:25,317 [Thread-7:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uploads/2017/04/login.jpg/
2017-04-15 15:04:36,714 [Thread-8:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uploads/
2017-04-15 15:05:11,112 [Thread-9:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uploads/avatar/2017/04/login.jpg
2017-04-15 15:05:32,464 [Thread-10:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uploads/avatar/2017/04/login.jpg/
2017-04-15 15:05:50,553 [Thread-2:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uploads/avatar/2017/04/login.jpg/
2017-04-15 15:07:58,270 [Thread-3:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uploads/
2017-04-15 15:09:11,505 [Thread-4:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uploads/
2017-04-15 15:09:49,673 [Thread-2:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /uploads/avatar/2017/04/login.jpg
2017-04-15 15:16:36,822 [Thread-8:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/uploads
2017-04-15 15:17:52,054 [Thread-13:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/uploads/avatar/2017/04/login.jpg/
2017-04-15 15:23:50,909 [Thread-2:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/uploads/avatar/2017/04/login.jpg/
2017-04-15 15:24:31,296 [Thread-5:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/uploads/avatar/
2017-04-15 15:24:33,823 [Thread-6:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/uploads/avatar/
2017-04-16 04:35:45,640 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-16 05:51:46,529 [Thread-5:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /admin/upload/kindeditor
2017-04-16 05:54:19,510 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/upload/kindeditor
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = self.process_request(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/admin/upload/kindeditor/?dir=image (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2017-04-16 06:04:58,619 [Thread-8:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-16 10:15:57,665 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 15, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 201, in render
    template = context.template.engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 574, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 3: 'static'. Did you forget to register or load this tag?
2017-04-16 11:45:11,334 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 38, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: ' : 'Y-m-d'' from 'item.date_publish|date : 'Y-m-d''
2017-04-16 11:46:39,350 [Thread-3:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 38, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: ': 'Y-m-d'' from 'item.date_publish | date: 'Y-m-d''
2017-04-16 12:28:35,904 [Thread-23:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-16 12:30:52,974 [Thread-30:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-16 15:28:51,385 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 54, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 152, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 149, in get_parent
    return self.find_template(parent, context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 129, in find_template
    template_name, skip=history,
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: slice requires 2 arguments, 1 provided
2017-04-16 15:29:28,135 [Thread-5:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 54, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 152, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 149, in get_parent
    return self.find_template(parent, context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 129, in find_template
    template_name, skip=history,
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: slice requires 2 arguments, 1 provided
2017-04-16 16:19:18,065 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/
2017-04-17 04:43:42,276 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 55, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 201, in render
    template = context.template.engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '% if add_path %}{{ add_path' from '% if add_path %}{{ add_path'
2017-04-17 04:43:43,120 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-17 06:24:17,925 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/archive/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 67, in archive
    return render(request, 'blog/index.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print [Article.objicts.get(pk=comm['article']) for comm in comm_list]
AttributeError: type object 'Article' has no attribute 'objicts'
2017-04-17 06:24:34,675 [Thread-7:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/archive/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 67, in archive
    return render(request, 'blog/index.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print [Article.objicts.get(pk=comm['article']) for comm in comm_list]
AttributeError: type object 'Article' has no attribute 'objicts'
2017-04-17 06:24:47,598 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-17 06:47:06,946 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/archive/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 69, in archive
    return render(request, 'blog/index.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print Article.objects.filter(comment_set_article="").query
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 796, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 814, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1133, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1019, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1327, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'comment_set_article' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2017-04-17 06:47:29,413 [Thread-3:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/archive/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 69, in archive
    return render(request, 'blog/index.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print Article.objects.filter(comment_set_article="").query
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 796, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 814, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1133, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1019, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1327, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'comment_set_article' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2017-04-17 06:47:33,642 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/archive/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 69, in archive
    return render(request, 'blog/index.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print Article.objects.filter(comment_set__article="").query
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 796, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 814, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1133, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1019, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1327, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'comment_set' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2017-04-17 07:00:30,838 [Thread-8:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/archive/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 69, in archive
    return render(request, 'blog/index.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print Article.objects.filter(comment_set__article="").query
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 796, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 814, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1133, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1019, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Library/Python/2.7/site-packages/django/db/models/sql/query.py", line 1327, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'comment_set' into field. Choices are: category, category_id, click_count, comment, content, date_publish, desc, id, is_recommend, tag, title, user, user_id
2017-04-17 07:00:42,230 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/archive/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 69, in archive
    return render(request, 'blog/index.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print Article.objects.all().comment_set.values('article').annotate(Count('article')).query
AttributeError: 'QuerySet' object has no attribute 'comment_set'
2017-04-17 07:01:36,751 [Thread-6:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/archive/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 69, in archive
    return render(request, 'blog/index.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print Article.objects.all().comment_set.values('article').annotate(Count('article')).query
AttributeError: 'QuerySet' object has no attribute 'comment_set'
2017-04-17 07:01:39,356 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/archive/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 69, in archive
    return render(request, 'blog/index.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print (Article.objects.all()).comment_set.values('article').annotate(Count('article')).query
AttributeError: 'QuerySet' object has no attribute 'comment_set'
2017-04-17 07:01:55,467 [Thread-4:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/archive/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 69, in archive
    return render(request, 'blog/index.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print (Article.objects.all()).comment_set.values('article').annotate(Count('article')).query
AttributeError: 'QuerySet' object has no attribute 'comment_set'
2017-04-17 07:02:01,564 [Thread-5:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 58, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print (Article.objects.all()).comment_set.values('article').annotate(Count('article')).query
AttributeError: 'QuerySet' object has no attribute 'comment_set'
2017-04-17 07:02:41,048 [Thread-6:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 58, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print (Article.objects.all()).comment_set.values('article').annotate(Count('article')).query
AttributeError: 'QuerySet' object has no attribute 'comment_set'
2017-04-17 07:02:43,764 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 58, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Library/Python/2.7/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 23, in global_setting
    print (Article.objects.all()).comment_set.all().query
AttributeError: 'QuerySet' object has no attribute 'comment_set'
2017-04-17 07:23:53,635 [Thread-2:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-17 08:01:24,594 [Thread-10:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-17 08:13:16,637 [Thread-49:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:14:33,498 [Thread-55:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:14:35,777 [Thread-57:123145323335680] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:16:30,213 [Thread-66:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:16:32,315 [Thread-68:123145323335680] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:16:44,019 [Thread-73:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:18:12,388 [Thread-77:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:18:15,092 [Thread-79:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:18:43,723 [Thread-82:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:22:05,702 [Thread-84:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:22:11,008 [Thread-85:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-17 08:27:55,524 [Thread-88:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:28:41,666 [Thread-89:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-17 08:29:21,022 [Thread-92:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:29:52,121 [Thread-94:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:31:40,365 [Thread-96:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:33:48,514 [Thread-98:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:37:29,000 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 56, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 439, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 392, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
NoReverseMatch: Reverse for 'article' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-04-17 08:38:49,380 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 56, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 439, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 392, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
NoReverseMatch: Reverse for 'article' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-04-17 08:40:08,232 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 56, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 439, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 392, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
NoReverseMatch: Reverse for 'article' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-04-17 08:41:09,484 [Thread-4:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 56, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 439, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 392, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
NoReverseMatch: Reverse for 'article' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-04-17 08:41:12,918 [Thread-5:123145314922496] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 56, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: ''archive' from ''archive'
2017-04-17 08:51:15,495 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/&id=2
2017-04-17 08:51:33,462 [Thread-8:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/&id=2
2017-04-17 08:51:48,697 [Thread-16:123145319129088] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:54:33,778 [Thread-9:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 08:55:55,620 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/index/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 56, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 439, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 392, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
NoReverseMatch: Reverse for 'article' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-04-17 09:00:22,342 [Thread-4:123145319129088] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 09:05:40,304 [Thread-4:123145319129088] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 09:07:02,104 [Thread-13:123145331748864] [django.request:152]             [base:get_response] [WARNING]- Not Found: /app/
2017-04-17 09:09:27,817 [Thread-2:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /app/
2017-04-17 09:10:01,169 [Thread-2:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /app/
2017-04-17 09:10:45,644 [Thread-10:123145319129088] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 09:17:03,479 [Thread-13:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 09:17:05,252 [Thread-15:123145323335680] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 09:22:24,822 [Thread-20:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-17 09:22:25,126 [Thread-21:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-17 09:22:25,623 [Thread-24:123145327542272] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-17 09:34:13,696 [Thread-7:123145323335680] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-17 09:34:14,104 [Thread-8:123145327542272] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-17 09:34:23,917 [Thread-12:123145327542272] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-17 09:36:57,823 [Thread-5:123145323335680] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 09:39:55,956 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 09:40:09,588 [Thread-9:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 09:43:46,224 [Thread-4:123145319129088] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 09:47:31,637 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 09:48:09,262 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_response(request, response)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 115, in process_response
    if response.status_code == 404:
AttributeError: 'dict' object has no attribute 'status_code'
2017-04-17 09:50:00,801 [Thread-8:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_response(request, response)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 115, in process_response
    if response.status_code == 404:
AttributeError: 'dict' object has no attribute 'status_code'
2017-04-17 10:03:43,753 [Thread-4:123145319129088] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 10:04:33,529 [Thread-3:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 10:09:39,293 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 10:11:27,933 [Thread-9:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 10:11:55,552 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 10:12:31,901 [Thread-8:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /admin/
2017-04-17 10:13:15,690 [Thread-15:123145319129088] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 10:15:15,047 [Thread-18:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 10:15:23,975 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 10:23:40,321 [Thread-9:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 10:23:52,604 [Thread-4:123145319129088] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/images/default.jpg
2017-04-17 10:26:59,800 [Thread-7:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 77, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: Could not parse the remainder: '/default.jpg' from 'images/default.jpg'
2017-04-17 10:52:19,459 [Thread-27:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 77, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
my
static
staticfiles
tz
2017-04-17 10:55:07,584 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 77, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/Library/Python/2.7/site-packages/django/template/utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "/Library/Python/2.7/site-packages/django/template/utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 31, in __init__
    super(DjangoTemplates, self).__init__(params)
  File "/Library/Python/2.7/site-packages/django/template/backends/base.py", line 29, in __init__
    "Unknown parameters: {}".format(", ".join(params)))
ImproperlyConfigured: Unknown parameters: TEMPLATE_LOADERS
2017-04-17 10:55:32,709 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 77, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/Library/Python/2.7/site-packages/django/template/utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "/Library/Python/2.7/site-packages/django/template/utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 31, in __init__
    super(DjangoTemplates, self).__init__(params)
  File "/Library/Python/2.7/site-packages/django/template/backends/base.py", line 29, in __init__
    "Unknown parameters: {}".format(", ".join(params)))
ImproperlyConfigured: Unknown parameters: LOADERS
2017-04-17 11:02:19,204 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 77, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
my
static
staticfiles
tz
2017-04-17 11:04:18,199 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 77, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
my
static
staticfiles
tz
2017-04-17 11:05:20,600 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 77, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
my
static
staticfiles
tz
2017-04-17 11:05:49,583 [Thread-4:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 77, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TemplateSyntaxError: 'myfilter' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
my
static
staticfiles
tz
2017-04-17 12:12:36,853 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 121, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/defaulttags.py", line 439, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Python/2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Library/Python/2.7/site-packages/django/urls/resolvers.py", line 392, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns)
NoReverseMatch: Reverse for 'logout' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
2017-04-17 12:19:58,198 [Thread-4:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/index/
2017-04-17 12:20:06,332 [Thread-9:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/index/
2017-04-17 12:23:16,986 [Thread-26:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/article/
2017-04-17 12:24:09,808 [Thread-33:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/article/article/
2017-04-17 12:30:36,178 [Thread-3:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /article/
2017-04-17 12:30:58,990 [Thread-10:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /article/
2017-04-17 12:56:41,662 [Thread-25:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /admin/
2017-04-17 12:56:43,041 [Thread-26:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /admin/
2017-04-17 17:03:42,382 [Thread-27:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-17 19:34:23,995 [Thread-5:123145323335680] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-17 21:11:30,441 [Thread-18:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-17 21:34:13,817 [Thread-2:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/index/
2017-04-17 21:36:34,507 [Thread-7:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-17 21:45:39,638 [Thread-14:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 123, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 1044, in render
    output = self.filter_expression.resolve(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 739, in resolve
    new_obj = func(obj, *arg_vals)
  File "/Users/yujian/local/DjangoTest/blog/templatetags/myfilter.py", line 9, in first_up
    return ['一', '二', '三', '四', '五', '六', '七', '八', '九', '十', '十一', '十二'][key.month - 1]
AttributeError: 'str' object has no attribute 'month'
2017-04-19 06:24:08,454 [Thread-6:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-19 06:27:04,288 [Thread-7:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /app/index/user
2017-04-19 06:30:58,365 [Thread-6:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /app/index/user
2017-04-19 06:31:28,236 [Thread-10:123145323335680] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /app/base/user/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/app/views.py", line 48, in user
    data = User.objects.all()
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 198, in __get__
    cls._meta.swapped,
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'blog.User'
2017-04-19 06:32:35,178 [Thread-2:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /app/base/
2017-04-19 06:32:42,582 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/index/
2017-04-19 06:32:51,677 [Thread-6:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/index/
2017-04-19 06:38:09,386 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 123, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
TypeError: test() takes exactly 1 argument (2 given)
2017-04-19 06:40:19,499 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/article/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 123, in article
    return render(request, 'blog/article.html', locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
AttributeError: 'Token' object has no attribute 'upper'
2017-04-19 08:49:57,585 [Thread-3:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-19 10:34:12,496 [Thread-2:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /app/base/
2017-04-19 10:34:12,546 [Thread-3:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2017-04-19 10:34:12,548 [Thread-4:123145314922496] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-19 10:34:12,601 [Thread-5:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2017-04-19 10:34:12,616 [Thread-6:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /app/base/
2017-04-19 10:34:12,634 [Thread-7:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2017-04-19 10:34:12,645 [Thread-8:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2017-04-19 10:34:13,718 [Thread-9:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /app/base/
2017-04-19 10:34:13,769 [Thread-10:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /favicon.ico
2017-04-19 10:34:13,903 [Thread-11:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2017-04-19 10:34:13,913 [Thread-12:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2017-04-19 10:34:17,481 [Thread-13:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /app/base/
2017-04-19 10:34:18,660 [Thread-14:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-19 10:34:20,390 [Thread-15:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /app/base/
2017-04-19 10:49:55,487 [Thread-7:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-19 10:51:48,605 [Thread-32:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-19 12:47:15,236 [Thread-10:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = self.process_request(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/blog/ajax/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2017-04-19 12:48:29,230 [Thread-3:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = self.process_request(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/blog/ajax/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2017-04-19 12:51:06,878 [Thread-3:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = self.process_request(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/blog/ajax/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2017-04-19 12:52:20,848 [Thread-5:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/ajax/blog/ajax
2017-04-19 12:52:43,475 [Thread-7:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = self.process_request(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/blog/ajax/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2017-04-19 12:53:52,347 [Thread-9:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = self.process_request(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/blog/ajax/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2017-04-19 12:54:18,765 [Thread-11:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = self.process_request(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/blog/ajax/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2017-04-19 12:54:52,696 [Thread-13:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = self.process_request(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/blog/ajax/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2017-04-19 13:57:25,525 [Thread-14:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = self.process_request(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/blog/ajax/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2017-04-19 14:06:54,918 [Thread-4:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/blog/ajax
2017-04-19 14:08:49,236 [Thread-9:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /
2017-04-19 14:09:05,480 [Thread-12:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = self.process_request(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/blog/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2017-04-19 14:09:23,807 [Thread-15:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/
2017-04-19 14:10:00,201 [Thread-18:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /ajax/
2017-04-19 14:10:52,867 [Thread-26:123145310715904] [django.request:152]             [base:get_response] [WARNING]- Not Found: /ajax/
2017-04-19 14:11:08,471 [Thread-29:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/ajax/
2017-04-19 14:12:52,341 [Thread-32:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/ajax/
2017-04-19 14:14:54,218 [Thread-35:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/ajax/
2017-04-19 14:16:14,830 [Thread-38:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/ajax/
2017-04-19 14:17:03,448 [Thread-41:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/ajax/
2017-04-19 14:17:20,072 [Thread-44:123145319129088] [django.request:152]             [base:get_response] [WARNING]- Not Found: /blog/ajax/ajax/
2017-04-19 14:18:00,703 [Thread-50:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/ajax/
2017-04-19 14:18:14,395 [Thread-55:123145327542272] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/
2017-04-19 14:20:13,973 [Thread-61:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/
2017-04-19 14:25:20,096 [Thread-64:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/
2017-04-19 14:27:48,261 [Thread-67:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/
2017-04-19 14:28:08,316 [Thread-68:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/
2017-04-19 14:30:47,742 [Thread-4:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/
2017-04-19 14:31:23,021 [Thread-5:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 78, in index
    return render(request, "blog/index.html", locals())
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Library/Python/2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 152, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 149, in get_parent
    return self.find_template(parent, context)
  File "/Library/Python/2.7/site-packages/django/template/loader_tags.py", line 129, in find_template
    template_name, skip=history,
  File "/Library/Python/2.7/site-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Library/Python/2.7/site-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Library/Python/2.7/site-packages/django/template/base.py", line 574, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
TemplateSyntaxError: Invalid block tag on line 27: 'crsf_token'. Did you forget to register or load this tag?
2017-04-19 14:32:00,894 [Thread-8:123145310715904] [django.request:158]             [csrf:_reject] [WARNING]- Forbidden (CSRF token missing or incorrect.): /blog/
2017-04-19 15:02:01,197 [Thread-4:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 229, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:03:16,495 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:04:51,415 [Thread-4:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:05:44,016 [Thread-26:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:06:11,668 [Thread-4:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:07:47,998 [Thread-5:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:09:48,705 [Thread-4:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:10:17,333 [Thread-6:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:10:48,232 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:10:55,497 [Thread-3:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:14:57,495 [Thread-4:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:21:05,860 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:21:08,611 [Thread-3:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 230, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:29:52,240 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 234, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:29:57,513 [Thread-3:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 234, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:30:16,618 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 234, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:30:27,520 [Thread-3:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 234, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:30:56,768 [Thread-4:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 234, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:31:42,053 [Thread-3:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 233, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:32:56,660 [Thread-26:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 234, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:48:11,028 [Thread-5:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 233, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:48:46,439 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 234, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:56:36,736 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 15:56:39,016 [Thread-3:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:28:02,562 [Thread-13:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 237, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:42:13,282 [Thread-33:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 237, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:43:25,089 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:44:55,757 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:45:51,961 [Thread-3:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:47:58,043 [Thread-6:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:48:06,915 [Thread-7:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:49:10,682 [Thread-10:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:51:01,483 [Thread-13:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:51:51,316 [Thread-21:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:53:39,199 [Thread-26:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:54:54,885 [Thread-27:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:55:28,348 [Thread-29:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 236, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:56:31,900 [Thread-5:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 237, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:56:57,588 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 238, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 16:57:52,138 [Thread-2:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 240, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
2017-04-19 17:01:47,794 [Thread-4:123145310715904] [django.request:132]             [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /blog/ajax/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yujian/local/DjangoTest/blog/views.py", line 238, in ajax
    return render(request, "/blog/index.html")
  File "/Library/Python/2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Library/Python/2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: /blog/index.html
